name: Deploy
on:
  push:
    tags:
    - 'v*'
    - '!v*-alpha'
jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout src
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_KEY}}
        heroku_app_name: "covfefeshop"
        heroku_email: "syahawesome@gmail.com"
        branch: ${{ github.ref_name }}